### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by LVerhulst4321**
Updated bug fixes pull request.

### CODE REVIEW

**Comment by LVerhulst4321** [comment]
I put your code change into place and I am only getting a single column to display. How does the code know how many items should be in a column?

**Comment by LVerhulst4321** [comment]
Nevermind. I figured out that the css file wasn't getting reloaded and I have to clear the old version out first. It is now displaying the items in 3 columns. Looks nice!

**Comment by olszowka** [comment]
Shall I merge the branch that way?  It will replace your pull request, but
will include your fixes to the link in the navbar.

  --PeterO

**Comment by LVerhulst4321** [comment]
Yes, please merge the branch with your new change. I am also working on implementing that change in my new optional "Interests" feature.

**Comment by olszowka** [comment]
Replaced with another PR.

**Pull request closed without merging**
